# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'WijekoonWHMCB-COBSCCOMP191P-006' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WijekoonWHMCB-COBSCCOMP191P-006
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  target 'WijekoonWHMCB-COBSCCOMP191P-006Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WijekoonWHMCB-COBSCCOMP191P-006UITests' do
    # Pods for testing
  end

end
